### ISSUE TITLE
Plant Care Reminder

### ISSUE THREAD

**Issue by Alphawave1989** [Fabi911/Capstone_Plant_Care#12]
## Value proposition
As a busy plant owner,

I want to receive care reminders for my plants,

so that I can ensure they are properly cared for without having to remember everything.
## Description

![Image](https://github.com/Fabi911/Capstone_Plant_Care/assets/158016538/3b065c96-280d-46fd-bf3f-ce003da712f2)

## Acceptance criteria
- [ ] Users can set an interval the watering schedule of each plant.
water daily
water every 2 days
water 3 times per week
water once per week
water every 2 weeks
water once per month
- [ ] Depending on the watering schedule the plant gets sorted into a list of plants that is generated on a daily basis.
- [ ] Users can aditionally set a reminder for fertilizing the plant.
fertilize every week
fertilize once per month
fertilize every 2 months
- [ ] Users can easily view which plants they need to water and fertize on a given day. (potentially on a seperate page)
## Tasks
- [ ] Create feature branch feature/plant-care-reminders
- [ ] Create a page Reminder.js , that displays plants you want to water today
- [ ] Create a component WateringSchedule.js, that handles watering times
- [ ] Create a component FertilizingSchedule.js, that handles ferilization times
