### ISSUE TITLE
Overview of Plants

### ISSUE THREAD

**Issue by Alphawave1989** [Fabi911/Capstone_Plant_Care#2]
Overview of Plants

## Value proposition
As a plant enthusiast,

I want to see a list of plants,

so that I can browse through the collection to get inspiration for new plants.

## Description

![Image](https://github.com/Fabi911/Capstone_Plant_Care/assets/148874065/08605313-5022-4c66-82c9-fdbfded10c7f)

## Acceptance criteria
- [ ] A clear and concise list of all plants (API data or data from [plants.json](https://github.com/neuefische/hh-web-24-1/blob/main/capstone-projects/plant-care/plants.json)) is displayed upon starting the App
- [ ] Each plant entry must include the name and the botanical name
- [ ] The list should be vertically scrollable to accommodate a large number of plants.
## Tasks
- [ ]  Create feature branch feature/overview-plants
- [ ] import data from [plants.json](https://github.com/neuefische/hh-web-24-1/blob/main/capstone-projects/plant-care/plants.json)
 tbc. from the team
- [ ] Create a plantList.js in your pages
- [ ] Create a plantPreview.js 
- [ ] render the plant items on your plantList page
