### ISSUE TITLE
Plant Details

### ISSUE THREAD

**Issue by Alphawave1989** [Fabi911/Capstone_Plant_Care#3]
## Value proposition
As a plant lover,

I want to access detailed information about each plant in the overview,

so that I can get a better understanding of the plant's needs and care requirements.
## Description

![Image](https://github.com/Fabi911/Capstone_Plant_Care/assets/148874065/2318a143-1058-420a-8a13-8b8c8566e5a1)

## Acceptance criteria
- [ ] Selecting a plant from the plants opens a detailed view containing:
the name,
the botanical name,
the water needs, and
the fertiliser season
- [ ] Add some more information (you might need to edit the plants.json file) like for example care instructions and light needs
- [ ] The detailed view includes a "Back" link or button, allowing users to easily navigate back to their personal list or the main list of plants.
## Tasks
- [ ] create feature branch feature/plant-details
- [ ] create folder plants/[id]
- [ ] create index.js in plants/[id]
- [ ] create function to call PlantDetail.js  by useRouter
- [ ] create a button or link to return to the overview page or personal list and vice versa
- [ ] create component PlantDetail.js to render a plant item
