### ISSUE TITLE
Responsive Design

### ISSUE THREAD

**Issue by HenrikBischkopf** [Fabi911/Capstone_Plant_Care#31]
## Value proposition
As a user
I want to be able to easy and comfortly access the app on all common mobiles
in order to effortlessy run the webApp.
## Description
- The interface should be similar on most common mobile devices.

## Acceptance criteria
- [ ] Visual simularity between different mobile devices in dev modus on browsers.
- [ ] Shouldnt have visual faults, like not centered texts, overlapping icons etc.

## Tasks
- [ ] code a responsive design in your global css, e.g. media querries.
