### ISSUE TITLE
Backend integration

### ISSUE THREAD

**Issue by HenrikBischkopf** [Fabi911/Capstone_Plant_Care#36]
## Value proposition
As a user,
I want to have an easy access to my personal plants on all devices,
in order to use it in different places, e.g. in my garden on my smartphone , on my couch on my laptop.
## Description
- allow for a Backend to ensure same access on all devices
## Acceptance criteria
- [ ] Can access MyPlants on different devices
## Tasks
- [ ] Create feature branch feature/backend-inegration
- [ ] implement a backend , where you put your DB. (MongoDB , Cloudinary?) and fetch your data from there.
