### ISSUE TITLE
Create Plant notes

### ISSUE THREAD

**Issue by Alphawave1989** [Fabi911/Capstone_Plant_Care#37]
Create Plant notes

## Value proposition

**As a user**,
**I want to** be able to log notes about my plants over time,
**So that I** can have a clear understanding of their health, needs and progress. 

## Description
![Image](https://github.com/Fabi911/Capstone_Plant_Care/assets/147390260/f14a2ef6-3ee7-41b3-980b-b91988c7fd65)

## Acceptance criteria
- [ ] Users can create notes for their plant´s to log the process of the grow
- [ ] Each plant entry must have at least 1 characters 
- [ ] The maximum of characters should be 250 
## Tasks
- [ ] Create feature branch feature/create-plant-notes
- [ ] Create a input field to edit commit with at least 1 character and max 250
- [ ] Create a button to submit the comment
