### ISSUE TITLE
Delete plant note

### ISSUE THREAD

**Issue by Alphawave1989** [Fabi911/Capstone_Plant_Care#38]
Delete plant note

## Value proposition
As a plant enthusiast,

I want to be able to delete my notes. 

## Description

![Image](https://github.com/Fabi911/Capstone_Plant_Care/assets/147390260/c58529c8-ad24-4615-aaae-970ce34bdfdb)

## Acceptance criteria
- [ ] Users can delete notes for their plant´s if they dont need the information anymore or entered wrong information
## Tasks
- [ ] Create feature branch feature/delete-notes
- [ ] Create a delete Button component for notes
- [ ] Implement the delete Button under each comment
