### ISSUE TITLE
Delete Plant Entries

### ISSUE THREAD

**Issue by Alphawave1989** [Fabi911/Capstone_Plant_Care#4]
## Value proposition
As a plant owner,

I want to delete plant entries from my plant collection,

so that I can keep my digital garden updated with only the plants I currently own.
## Description

![Image](https://github.com/Fabi911/Capstone_Plant_Care/assets/148874065/fc7a048e-e3b7-4c7d-9d6b-3e4941b22a06)

## Acceptance criteria
- [ ] Each listed plant on the "My plants page" includes an easily accessible "Delete" option.
- [ ] The "Delete" option is intuitive to find, perhaps represented by a trash can icon or a clearly labeled button.
- [ ] Clicking the "Delete" button triggers a confirmation dialog.
- [ ] The dialog serves to prevent accidental deletions by asking the user to confirm their intention.
- [ ] The dialog includes options for both confirming the deletion and cancelling the action.
- [ ] The cancellation option allows the user to back out of the deletion process if selected by mistake or changed mind.
- [ ] Upon deletion, the plant entry is immediately removed from the user's collection.
## Tasks
- [ ] Create feature branch feature/delete-plants
- [ ] Create a component named DeleteButton.js 
- [ ] Create a handle function named handleDelete with a confirmation
- [ ] PlantDetail need the deleteButton function
- [ ] redirect if user is on PlantDetail
