### ISSUE TITLE
Update plant note

### ISSUE THREAD

**Issue by Alphawave1989** [Fabi911/Capstone_Plant_Care#40]
Update plant note

## Value proposition
As a plant enthusiast,

I want to update my comment, 

if I made a mistake while typing or information is incorrect.

## Description

![Image](https://github.com/Fabi911/Capstone_Plant_Care/assets/147390260/9be312bb-8f43-4479-b68a-0d106e3613e0)

## Acceptance criteria
- [ ]  Users can edit notes for their plant´s if they dont need the information anymore or entered wrong information

## Tasks
- [ ]  Create feature branch feature/edit-notes
- [ ]  Create an edit Button component for notes
- [ ]  Implement the edit Button under each comment
