### ISSUE TITLE
Notifications with Toastify

### ISSUE THREAD

**Issue by Fabi911** [Fabi911/Capstone_Plant_Care#45]
## Value proposition
As a user
I want to see that my upload or adding works
In order to have a feedback on the screen.
## Description

![Image](https://github.com/Fabi911/Capstone_Plant_Care/assets/148874065/cdab5dad-5e9d-40a3-80d8-32a374443f7f)

## Acceptance criteria
- [ ] If I attempt to upload or add content without providing any data:
  - I should see an error message displayed on the screen indicating that content is required before proceeding.
- [ ] If I successfully upload or add content:
  - I should see a confirmation message displayed on the screen confirming that the action was successful.

## Tasks
- [ ] Create feature branch feature/toastify
- [ ] Integrate toastify
- [ ] add toast messages and toast container
