### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by Fabi911** [Fabi911/Capstone_Plant_Care#46]
As a user,
I want to have a secure and easy login system
In order to access the platform's features and personalized content.
##Description

![Image](https://github.com/Fabi911/Capstone_Plant_Care/assets/148874065/0906f37f-4ab2-4f9c-9fbd-357ed4291e8f)

##Acceptance criteria

- [ ] I should be able to see the login field on all protected sites, whenever I want to make profile related changes
- [ ] The login page should contain a button to sign in.
- [ ] if I am logged in I´ll see the current state (logged in as .....)

##Tasks

- [ ] set up Github Oauth with client and secret ID
- [ ] user collection in DB + model
- [ ] install next.auth 
- [ ] session context
