### ISSUE TITLE
Edit Plant Entries

### ISSUE THREAD

**Issue by Alphawave1989** [Fabi911/Capstone_Plant_Care#5]
## Value proposition
As a plant enthusiast,

I want to edit the details of my plant entries,

so that I can keep the information accurate and up to date.
## Description

![Image](https://github.com/Fabi911/Capstone_Plant_Care/assets/148874065/7c4c7eb5-9d4f-4400-9586-6da83aa13ccb)

![Image](https://github.com/Fabi911/Capstone_Plant_Care/assets/148874065/fe5d51cf-76e3-4a18-aa6f-5121fc36772a)

## Acceptance criteria
- [ ] Users can edit any detail of their plant entries, including name, botanical name, water needs, and fertiliser season.
- [ ] Users can easily edit the watering schedule and fertiliser schedule for each plant.
- [ ] The "Edit" option is intuitive to find, perhaps represented by a pencil icon or a clearly labeled button.
- [ ] Clicking "Edit" opens a form pre-filled with the plants's existing details for modification.
- [ ] The form section includes options for both saving and cancelling the action.
- [ ] The cancellation option allows the user to back out of the edit process if selected by mistake or their changed mind.
- [ ] Submissions with empty required fields are blocked, with validation messages guiding completion.
- [ ] Changes are saved and immediately reflected in the app.
- [ ] Users receive feedback on successful updates or errors in their entry form.
- [ ] 💡 Note the possibility to edit an entry could also be on the details view of the plant.
## Tasks
- [x] Create feature branch feature/edit-plants
- [ ] Create a page Plants/[id]/Edit.js ; add component Form to the Edit.js page
- [ ] Create a handleEdit function in _app.js
- [ ] Create a component EditButton.js and add it on the DetailPage
- [ ] Create a feedback function for succesful editing
