### ISSUE TITLE
Delete an Image in the  Gallery

### ISSUE THREAD

**Issue by Fabi911** [Fabi911/Capstone_Plant_Care#50]
## Value proposition
As a plant owner,

I want to delete image entries in the gallery from my plant detail page,

so that I can keep my gallery updated with only the images I currently want.
## Description

![Image](https://github.com/Fabi911/Capstone_Plant_Care/assets/148874065/e9c604ca-80ce-4984-a03c-30b936593808)

## Acceptance criteria
- [ ] Each listed image on the gallery includes an easily accessible "Delete" option.
- [ ] The "Delete" option is intuitive to find, perhaps represented by a trash can icon or a clearly labeled button.
- [ ] Clicking the "Delete" button triggers a confirmation dialog.
- [ ] The dialog serves to prevent accidental deletions by asking the user to confirm their intention.
- [ ] The dialog includes options for both confirming the deletion and cancelling the action.
- [ ] The cancellation option allows the user to back out of the deletion process if selected by mistake or changed mind.
## Tasks
- [ ] Create feature branch feature/delete-image
- [ ] Create a handle function named handleDeleteImage with a confirmation
