### ISSUE TITLE
Create Own Plant Entries

### ISSUE THREAD

**Issue by Alphawave1989** [Fabi911/Capstone_Plant_Care#6]
## Value proposition
As a plant hobbyist,

I want to add my own plant entries to the app,

so that I can track their care in a personalized manner.
## Description

![Image](https://github.com/Fabi911/Capstone_Plant_Care/assets/148874065/37aba21a-0ea1-4c64-9349-c9c420ba4885)

![Image](https://github.com/Fabi911/Capstone_Plant_Care/assets/148874065/eafb09c7-9d6e-4b6a-9309-d9535131d0c0)

## Acceptance criteria
- [x] Users can add new plant entries, specifying
the name,
the botanical name,
the water needs, and
the fertiliser season
- [x] All of the above fields are mandatory, with a character limit between 1 and 150.
- [x] Upon submission, the new plant entry is added to the top of the user's "My Plants" page or section.
- [x] Users receive feedback on successful addition or errors in their entry form.
- [x] Form submission with any empty mandatory fields is blocked, and clear validation messages indicate the fields that need completion.
## Tasks
- [ ] Create feature branch feature/add-plants
- [ ] Create component Form.js, set input required (all)
- [ ] Create component for SubmitButton.js and CancelButton.js 
- [ ] Create handle function feedback for success / fail / errors
- [ ] create page addPlants.js
- [ ] create function for adding plants
- [ ] create AddPlantButton.js and put it on the overview page and myplants page
