### ISSUE TITLE
Design Finish 💅

### ISSUE THREAD

**Issue by Alphawave1989** [Fabi911/Capstone_Plant_Care#62]
## Value proposition
As a plant enthusiast, 

I want to have a clear and structured design, 

so that the layout enhances navigation and usability

## Description

![Image](https://github.com/Fabi911/Capstone_Plant_Care/assets/147390260/96ac1948-8875-4a75-be54-8ba5488d77c2)

## Acceptance criteria
- [ ]  Users can effortlessly navigate the app, finding desired features and information.
- [ ]  Colors throughout the app complement the content
- [ ]  The app's design is responsive and compatible with various devices and screen sizes.
- [ ] Visual elements such as icons and imagery are consistent with the overall design theme and enhance user experience.

## Tasks
- [ ]  Create feature branch feature/design-finish
- [ ] Have a complete view over code and app
- [ ] adjust colors 
- [ ] adjust responsive design
