### ISSUE TITLE
Local Weather Integration

### ISSUE THREAD

**Issue by Alphawave1989** [Fabi911/Capstone_Plant_Care#65]
## Value proposition
As a plant lover,

I want to see the current weather information,

so that I can get a better feeling of my plant needs.
## Description

![Image](https://github.com/Fabi911/Capstone_Plant_Care/assets/147390260/3d5f247d-e781-4784-9195-049a054cf7eb)

## Acceptance criteria
- [ ] See the temperature that is currently available 
- [ ] See the weather condition with an icon 
## Tasks
- [ ] create feature branch feature/weather
- [ ] create folder weather
- [ ] create Weather.js in components/Weather
- [ ] create function Weather with useState, useSWR, useEffect to fetch the weather
