### ISSUE TITLE
Bug Fix

### ISSUE THREAD

**Issue by HenrikBischkopf** [Fabi911/Capstone_Plant_Care#68]
## Value proposition

As a user
I want to enjoy the app without bugs
In order to benefit from an easy access.

## Description

Fix some minor bug fixes:
- [ ] Semicolon beneath the calendar
- [ ] Old calendar library component on the watering page
- [ ] Allow return to general pages if access is denied

## Acceptance criteria

- [ ] Calendar page without Semicolon at the end
- [ ] No old calendar component on watering page
- [ ] Can access BackArrow component on pages i am not authorized to see content
 
## Tasks

- [ ] create a new branch feature/bugFix
- [ ] navigate through components and pages and adjust functions to remove minor bugs.
