### ISSUE TITLE
Image Upload with Cloudinary for My Plants

### ISSUE THREAD

**Issue by Alphawave1989** [Fabi911/Capstone_Plant_Care#7]
## Value proposition
As a plant collector,

I want to upload images of my plants,

so that I can represent my plants with their image and visually document their growth.
## Description
- Wireframe tbc.
## Acceptance criteria
- [x] Users can upload images for each plant entry in their "My Plants" page.
- [x] The app utilizes Cloudinary for efficient and secure image storage and management.
- [x] Users can view uploaded images in a gallery format within each plant's detail page.
- [x] When there is one image uploaded for a plant, it is displayed as a thumbnail in the list of my plants.
- [x] When there are multiple images uploaded for a plant, the User can select a thumbnail to represent the plant in the list of my plants.
- [x] The upload process includes feedback on successful uploads or error messages for failed attempts.
## Tasks
- [x] Create feature branch feature/image-upload-cloudinary
- [x] Integrate Cloudinary API for image uploads
- [x] Design and implement the UI for image upload and gallery view
- [x] tbc. from the team
