### ISSUE TITLE
login styling

### ISSUE THREAD

**Issue by HenrikBischkopf** [Fabi911/Capstone_Plant_Care#73]
## Value proposition

As a user
I want to easily recognize the login and logout feature
In order to benefit from an easy access.

## Description

Style the Login and Logout feature to easily recognize it.

## Acceptance criteria

- [ ] Login / Logout button is marked with a clearly identificable emoji.
 
## Tasks

- [ ] create a new branch feature/loginStyling
- [ ] use Styled Components to style the buttons, eventually flexboxes to order them, find a fitting emoji to insert
