### ISSUE TITLE
Calendar Redesign

### ISSUE THREAD

**Issue by HenrikBischkopf** [Fabi911/Capstone_Plant_Care#77]
## Value proposition

As a user
I want to enjoy the app with a clear and structured reminder calendar
In order to benefit from a good overview.

## Description

- [ ] Structure the calendar clearer
- [ ] Reassign colors for the text part

## Acceptance criteria

- [ ] Calendar page is more structured and easier to read

 
## Tasks

- [ ] create a new branch feature/CalendarRedesign
- [ ] adjust the calendar feature in the CalendarReminder component regarding flex-box and css-styles.
