### ISSUE TITLE
My Plants Page

### ISSUE THREAD

**Issue by Alphawave1989** [Fabi911/Capstone_Plant_Care#8]
## Value proposition
As a plant owner,

I want to have a dedicated space for my plants,

so that I can easily manage and view plants that I personally own
## Description

![Image](https://github.com/Fabi911/Capstone_Plant_Care/assets/148874065/9bbd392f-1663-45e7-abe1-5db8563fb480)

## Acceptance criteria
- [ ] Each listed plant includes an easily accessible option to add to a section or page called "My Plants"
- [ ] The "Add to My Plant" option is intuitive to find, perhaps represented by a plant icon and/or a clearly labeled button.
- [ ] This page/section displays all plants added by the user.
- [ ] Selected plants can be removed from the "My Plants List" using the button.
- [ ] Users can view, access, and manage their saved plants in this section.
- [ ] The plants selected as "My Plants" are visually highlighted (e.g., icon color)
- [ ] It is also possible to mark an entry as "my plant" in the detailed view of each plant.
## Tasks
- [ ] Create feature branch feature/my-plants
- [ ] create component Navbar.js
- [ ] create ownedPage.js
- [ ] create function for add plants to my ownedPage
- [ ] create component OwnedPlantButton.js
- [ ] add OwendPlantButton to detail page, overview page and myPlants page
